config/routes.rb
AstronomWeb::Application.routes.draw do

    resources :meals, :foods, :astronauts

    get 'inventory' => 'inventory#inventory'

    get '/day_snapshots/:name',
        to: 'snapshots#show',
        defaults: {
          end_time:   Time.now.to_s,
          start_time: (Time.now - 1.day).to_s
        }

    get '/week_snapshots/:name',
        to: 'snapshots#show',
        defaults: {
          end_time:   Time.now.to_s,
          start_time: (Time.now - 1.week).to_s,
          interval_in_minutes: 15
        }

    get '/snapshots/:id',
        to: 'snapshots#show'

    get '/review' => "static#review"
    root 'static#landing'

end

app/models/food.rb
class Food < ActiveRecord::Base

  DEFAULT_QUANTITY = 50

  has_many :meals

  store_accessor :nutrition, :sodium, :protien # Add more nutrition options here!


  def self.build_from_upc(name: )
    create(
      name: name,
      display_name: name.titleize,
      upc: name,
      quantity: DEFAULT_QUANTITY)
  end


  def self.build_other(name: )
    create(
      name: name,
      display_name: name.titleize,
      quantity: DEFAULT_QUANTITY)
  end

  def nutrients?
      nutr = []

      # sort out units
      nutrient_table = {}

      self.nutrition.each do |n|
          nutrient_name = n[0].chomp("_units")

          nutrient_table[nutrient_name] ||= {}

          if nutrient_name != n[0]
            # handle units measure 
            nutrient_table[nutrient_name]["units"] = n[1]
          else
             #handle amount
            nutrient_table[nutrient_name]["amount"] = n[1]
          end
      end

      nutrient_table.each do |n|
          nutr << n
      end
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def create
    food = Food.new(params: params)

    respond_to do |format|
      if food.valid?
        if food.commit!
          format.json { head :ok }
        else
          format.json { head :not_acceptable }
        end
      else
        format.json { head :not_acceptable }
      end
    end
  end

  def new
  end

  def show
    params.permit(:id, :format)
    @food = Food.where(id: params[:id]).first
    gon.nutrients = @food.nutrients?

    respond_to do |format|
      format.html { render "show", layout: "callout"}
      format.json { render json: FoodWithNutrition.new(@food).as_json }
    end
  end

  def index
      @foods = Food.order(:quantity).page params[:page]

      respond_to do |format|
        format.html
      end
  end

end

app/views/foods/index.html.erb
<h1>Inventory</h1>

<div class="inventory-pane">
    <div class="row">
        <div class="small-12 medium-12 large-12 columns">
            <%= paginate @foods %>
        </div>
    </div>
    <br>
    <div class="inventory-table">
        <div class="row inventory-table-header">
            <div class="small-2 medium-2 large-2 columns">
                <strong>UPC</strong>
            </div>
            
            <div class="small-7 medium-7 large-7 columns">
                <strong>Food Item</strong>
            </div>

            <div class="small-3 medium-3 large-3 columns">
                <div class="text-right">
                    <strong>Quantity</strong>
                </div>
            </div>
        </div>
        <% @foods.each do |f| %>
        <div class="row inventory-item">
            <div class="small-2 medium-2 large-2 columns">
                <span class="<%='all-out' if f.quantity == 0 %>">
                    <%= f.upc || "? ? ? "%>
                </span>
            </div>

            <div class="small-7 medium-7 large-7 columns">
                <span class="<%='all-out' if f.quantity == 0 %>">                
                    <%= link_to( food_path(f) , :data=>{:colorbox => true,
                                :colorbox_iframe=>true,
                                :colorbox_height=>"75%",
                                :colorbox_width=>"75%" }) do %>
                        <%= f.display_name %>
                    <% end %>
                </span>
            </div>

            <div class="small-3 medium-3 large-3 columns">
                <div class="text-right <%='all-out' if f.quantity == 0 %>">
                    <%= f.quantity %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/foods/new.html.erb
<h1>Add item to inventory</h1>

<%= form_for :food do |f| %>
    Food name: <%= f.text_field :display_name %>

    <%= f.submit %>
<% end %>

app/views/foods/show.html.erb
<div class="row food-info-header">
    <div class="row">
        <div class="small-6 medium-6 large-6 columns">
            <strong>Quantity remaining:</strong> <%= @food.quantity%>
        </div>
        <div class="small-6 medium-6 large-6 columns food-logistics-quantity">
            <strong>UPC:</strong> <%= @food.upc || "? ? ? "%>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-12 large-12 columns food-logistics-name">
            <%= @food.display_name %>
        </div>
    </div>
</div>
<div class="row" style="margin:10px;">
    <div class="small-6 medium-6 large-6 columns">
<div class="food-pane">
        <div>
            <% if @food.nutrients?["energy"] %>
            <h2><strong>Energy</strong> <%= "#{@food.nutrients?['energy']["amount"]} #{@food.nutrients?['energy']["units"]}"%>
            <% end %>
            <% if @food.nutrients?["water"] %>
            <h2><strong>Water</strong> <%= "#{@food.nutrients?['water']["amount"]} #{@food.nutrients?['water']["units"]}"%>
            <% end %>
            <% if @food.nutrients?["total_sugar"] %>
                <h2><strong>Sugar</strong> <%= "#{@food.nutrients?['total_sugar']["amount"]} #{@food.nutrients?['total_sugar']["units"]}"%>
            <% end %>
            <% if @food.nutrients?["carbohydrates"] %>
            <h2><strong>Carbs</strong> <%= "#{@food.nutrients?['carbohydrates']["amount"]} #{@food.nutrients?['carbohydrates']["units"]}"%>
            <% end %>
            <% if @food.nutrients?["sodium"] %>
            <h2><strong>Sodium</strong> <%= "#{@food.nutrients?['sodium']["amount"]} #{@food.nutrients?['sodium']["units"]}"%>
            <% end %>
        </div>
                <ul>
                    <div class="row">
                        <div class="small-6 medium-6 large-6 columns">
                            <strong>Nutrient: </strong>
                        </div>
                        <div class="small-6 medium-6 large-6 columns">
                            <strong>Amount: </strong>
                        </div>
                    </div>
                    <% @food.nutrients?.each do |n| %>
                    <div class="row">
                        <div class="small-6 medium-6 large-6 columns">
                            <%= n[0] %>
                        </div>
                        <div class="small-6 medium-6 large-6 columns">
                            <%= "#{n[1]["amount"]} #{n[1]["units"]}"%>
                        </div>
                    </div>
                    <% end %>
                </ul>
</div>
    </div>
	<div class="small-6 medium-6 large-6 columns">
        <div id="graph-container" style="width:400px; height:400px">		
        </div>
    </div>
</div>


<script>
(function basic_radar(container) {

  // Fill series s1 and s2.
  var data = [];
  var refdata = [];
  var ticks = [];
  var care_about = ["water", "energy", "sodium", "total_sugar", "carbohydrates"    ];
  var refval = {
	water: 3000.0,
	energy: 3200.0,
	sodium: 3000.0,
	total_sugar: 38.0,
	carbohydrates: 46.0
  }
  
  var i = 0;
  Object.keys(gon.nutrients).forEach( function (k) {
	  if (_.contains(care_about,k) ) {
          var nut = gon.nutrients[k];
          data.push( [i, nut.amount/refval[k]]);
          refdata.push( [i, 1] );
          ticks.push( [i, k] );
          i++;
      }
  });
  
  s1 = { data : data };
  s2 = { data : refdata };
    
  // Draw the graph.
  graph = Flotr.draw(container, [ s1, s2], {
    radar : { show : true}, 
    grid  : { circular : true, minorHorizontalLines : true}, 
    yaxis : { min : 0, max : 1.2, minorTickFreq : .2}, 
    xaxis : { ticks : ticks}
  });
})(document.getElementById("graph-container"));
</script>